version: 2
before:
  hooks:
    - go mod download
builds:
  - # Path to main.go file or main package.
    main: ./main.go
    # Custom environment variables to be set during the builds.
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    # GOOS list to build for.
    goos:
      - darwin
      - linux
      - windows
    # GOARCH to build for.
    goarch:
      - amd64
      - arm64
archives:
  - # Archive name template
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{.ShortCommit}}"
release:
  include_meta: true
  github:
    owner: AGou-ops
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
