name: build
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: dist/*.tar.gz
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
